---

dependency:
  name: galaxy
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          infoblox_nios_provider:
            host: puthere.yourserver.name
            username: ansible
            password: changeme
          infoblox_hosts:
            - name: ansible_test1.xunta.local
              state: present
              dns: false
              vlans:
                - vlanSupportDevMANAGSRV1
                - vlanApplicationDevGEN1
            - name: ansible_test2.xunta.local
              state: present
              dns: false
              vlans:
                - vlanSupportDevMANAGSRV1
                - vlanApplicationDevGEN1

          infoblox_vlans:
            - name: vlanApplicationDevGEN1
              id: 1454
              cidr: 20
              gateway: 10.112.64.1

            - name: vlanBackEndDevDBMS1
              id: 1654
              cidr: 21
              gateway: 10.113.32.1

            - name: vlanSupportDevBACKUP1
              id: 1877
              cidr: 18
              gateway: 10.119.128.1

            - name: vlanSupportDevMONITOR1
              id: 1873
              cidr: 18
              gateway: 10.118.128.1

            - name: vlanSupportDevMANAGSRV1
              id: 1859
              cidr: 19
              gateway: 10.117.128.1

            - name: vlanSupportDevSTORNAS1
              id: 1889
              cidr: 20
              gateway: 10.116.224.1

            - name: vlanSupportDevSTORSAN1
              id: 1883
              cidr: 20
              gateway: 10.116.128.1

verifier:
  name: ansible
